pagination:
  blogs:
    per_page: 9
  properties:
    per_page:
      default: 16
      tablet: 15
      mobile: 10
  syndication:
    per_page: 9
truncate:
  blog:
    title: 60
    summary: 370
  property:
    title: 30