pagination:
  blogs:
    per_page: 9
  properties:
    per_page:
      default: 16
      tablet: 15
      mobile: 10
  syndication:
    per_page: 9
truncate:
  blog:
    title: 60
    summary: 370
    meta_description: 165
  property:
    title: 30
    listing_title: 42
  syndication:
    title: 48
meetup:
  group_urlname: wilson-investment-properties-inc
  per_page: 10
  OAuth_api_end_point: https://secure.meetup.com/oauth2/access
  redirect_uri_develop: https://8dda133b.ngrok.io/oauth2/meetup_api
  redirect_uri_production: https://www.wilsoninvest.com/oauth2/meetup_api
  authorize_end_point: https://secure.meetup.com/oauth2/authorize